apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: student-portal
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "YOUR_ACCESS_KEY_HERE"
  AWS_SECRET_ACCESS_KEY: "YOUR_SECRET_KEY_HERE"